// /today — server component that inlines the day's daily HTML
// inside the spanda app shell.
//
// Reads ${DAILY_ROOT}/YYYY/MM/DD.html from disk on the same VPS as
// the existing personal-os daily-review pipeline. Falls back to the
// most-recent prior daily within 7 days; renders an empty state if
// no daily found at all.
//
// Per phase2.html locked decision: server-side disk read, NOT
// HTTP fetch or iframe embed.

import { existsSync, readFileSync } from "node:fs";
import { loadDailyHtml, type DailyLoaderFs } from "@/lib/daily-loader";

// Configurable root. Default mirrors the live VPS path used by the
// daily-review pipeline; override with SPANDA_DAILY_ROOT for tests
// or alternate deployments.
const DAILY_ROOT = process.env.SPANDA_DAILY_ROOT
  || "/home/deploy/code/html-artifacts/docs/daily";

const realFs: DailyLoaderFs = {
  exists: (path) => existsSync(path),
  read: (path) => readFileSync(path, "utf8"),
};

export default async function TodayPage() {
  let body = "";
  let usedDate = "";
  let fellBack = false;
  let title: string | null = null;
  let loadError: string | null = null;

  try {
    const result = loadDailyHtml({
      root: DAILY_ROOT,
      now: new Date(),
      fs: realFs,
    });
    body = result.body;
    usedDate = result.usedDate;
    fellBack = result.fellBack;
    title = result.title;
  } catch (err) {
    loadError = err instanceof Error ? err.message : String(err);
  }

  return (
    <main className="min-h-screen bg-paper-100 px-6 py-8">
      <div className="max-w-[1200px] mx-auto">
        <header className="mb-6 pb-4 border-b border-paper-200">
          <div className="flex items-baseline justify-between gap-4">
            <h1 className="text-3xl font-display font-black text-ink-900 tracking-tight">
              Today
            </h1>
            {usedDate && (
              <div className="text-sm text-ink-700">
                {fellBack ? (
                  <span className="inline-flex items-center gap-2">
                    <span
                      className="inline-block w-2 h-2 rounded-full bg-ochre-500"
                      aria-hidden
                    />
                    showing <strong className="text-ink-900">{usedDate}</strong>
                    {" "}(most recent daily)
                  </span>
                ) : (
                  <>generated <strong className="text-ink-900">{usedDate}</strong></>
                )}
              </div>
            )}
          </div>
          {title && (
            <p className="text-sm text-ink-700 mt-2">{title}</p>
          )}
        </header>

        {loadError ? (
          <div className="rounded-2xl bg-paper-50 p-8 text-center">
            <p className="text-ink-700 text-base">
              No daily review found in the last 7 days.
            </p>
            <p className="text-ink-500 text-sm mt-2 font-mono">
              {loadError}
            </p>
            <p className="text-ink-700 text-sm mt-4">
              Run the personal-os daily-review pipeline to generate today&apos;s file.
            </p>
          </div>
        ) : (
          // The daily content is trusted (generated by our own pipeline,
          // not user input). Inline via dangerouslySetInnerHTML.
          <div
            className="daily-content"
            dangerouslySetInnerHTML={{ __html: body }}
          />
        )}
      </div>
    </main>
  );
}
