/**
 * F5 (iteration 2.2) — the daily-review HTML is embedded cleanly: its own
 * chrome (lockup/nav/footer) is stripped so there's one app bar, and its CSS
 * is scoped under `.daily-content` so it can't clash with the app shell.
 */

import { describe, expect, it } from "vitest";
import {
  stripDailyChrome,
  stripElement,
  scopeCss,
  sanitizeDaily,
} from "@/lib/daily-sanitize";

describe("stripElement", () => {
  it("removes a tag block by class token, depth-matching nested same-tags", () => {
    const html =
      `<div class="topbar"><div class="brand">spanda</div>` +
      `<button>Open setlist</button></div>` +
      `<div class="card">keep me</div>`;
    const out = stripElement(html, "div", "topbar");
    expect(out).toContain("keep me");
    expect(out).not.toContain("Open setlist");
    expect(out).not.toContain("brand");
  });

  it("matches the full class token only (not a substring)", () => {
    // `foot` must NOT strip `lane-foot`.
    const html = `<footer class="lane-foot">section foot</footer>`;
    expect(stripElement(html, "footer", "foot")).toContain("section foot");
  });
});

describe("stripDailyChrome", () => {
  it("strips div.topbar + footer.foot, KEEPS lane-head/lane-foot content", () => {
    // Mirrors the real daily: <header class="lane-head"> is a SECTION TITLE
    // (content); chrome is the topbar div + the page footer.foot.
    const html =
      `<div class="topbar"><span>spanda</span>` +
      `<button>Open setlist</button></div>` +
      `<header class="lane-head">REFLECT</header>` +
      `<section class="card">real content</section>` +
      `<footer class="lane-foot">view all 3</footer>` +
      `<footer class="foot">generated by pipeline</footer>`;
    const out = stripDailyChrome(html);
    // chrome gone
    expect(out).not.toContain("Open setlist");
    expect(out).not.toContain("generated by pipeline");
    // content kept (the regression this guards against)
    expect(out).toContain("REFLECT");
    expect(out).toContain("real content");
    expect(out).toContain("view all 3");
  });
});

describe("scopeCss", () => {
  it("prefixes plain selectors with the scope", () => {
    expect(scopeCss(".card { color: red }", ".daily-content")).toContain(
      ".daily-content .card",
    );
  });

  it("maps body/:root onto the scope container (no global leak)", () => {
    const out = scopeCss("body { margin: 0 } :root { --x: 1px }", ".dc");
    expect(out).toContain(".dc {");
    expect(out).not.toMatch(/(^|\s)body\s*\{/);
  });

  it("scopes rules inside @media, keeps the wrapper", () => {
    const out = scopeCss("@media (min-width: 700px) { .x { top: 0 } }", ".dc");
    expect(out).toContain("@media (min-width: 700px)");
    expect(out).toContain(".dc .x");
  });

  it("leaves @keyframes / @font-face selectors untouched", () => {
    const out = scopeCss("@keyframes spin { from { top: 0 } }", ".dc");
    expect(out).toContain("@keyframes spin");
    expect(out).not.toContain(".dc from");
  });

  it("hoists @import to the top and does NOT glue it to the next rule", () => {
    // The real-world killer: @import (statement, no block) immediately before
    // the :root token block. Must stay a standalone statement, and :root must
    // become its own scoped rule — otherwise every design token dies.
    const css = `@import url("https://f.co/x");\n:root{--c:#9fe870}\n.card{color:var(--c)}`;
    const out = scopeCss(css, ".dc");
    // @import preserved as a statement, first, ending in ';'
    expect(out).toMatch(/^@import url\("https:\/\/f\.co\/x"\);/);
    // it must NOT have been turned into a block rule
    expect(out).not.toMatch(/@import[^;]*\{/);
    // the token block survives, scoped onto the container
    expect(out).toMatch(/\.dc \{\s*--c:#9fe870/);
    expect(out).toContain(".dc .card");
  });

  it("keeps an @import whose URL contains semicolons intact (Google Fonts)", () => {
    // Real killer: the Google Fonts URL has `wght@400;500;600`. Splitting at
    // the first ';' truncated the @import mid-URL, dumped the tail into the
    // selector stream, and invalidated the ENTIRE stylesheet (0 parsed rules).
    const css =
      `@import url("https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap");\n` +
      `:root{--c:#9fe870}\n.card{color:var(--c)}`;
    const out = scopeCss(css, ".dc");
    // the @import is one intact statement on the first line, ending in ');'
    const firstLine = out.split("\n")[0];
    expect(firstLine).toBe(
      `@import url("https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap");`,
    );
    // no fragment of the URL leaked into a scoped selector
    expect(out).not.toContain(".dc 500;600");
    expect(out).not.toMatch(/\.dc[^{]*display=swap/);
    // the real rules survive
    expect(out).toMatch(/\.dc \{\s*--c:#9fe870/);
    expect(out).toContain(".dc .card");
  });

  it("preserves @font-face inner declarations and keeps it global", () => {
    const out = scopeCss(
      `@font-face{font-family:"M";src:url(a.woff2)}`,
      ".dc",
    );
    expect(out).toContain("@font-face");
    expect(out).toContain('font-family:"M"');
    expect(out).not.toContain(".dc @font-face");
  });
});

describe("sanitizeDaily", () => {
  const doc = `<!doctype html><html><head>
    <style>body{margin:0} .card{color:red}</style>
    </head><body>
    <div class="topbar"><span>spanda</span><button>Open setlist</button></div>
    <header class="lane-head">REFLECT</header>
    <section class="card">today content</section>
    </body></html>`;

  it("returns chrome-free content (keeps section titles) and scoped css", () => {
    const { content, css } = sanitizeDaily(doc);
    expect(content).toContain("today content");
    expect(content).toContain("REFLECT"); // section title kept
    expect(content).not.toContain("Open setlist"); // topbar chrome gone
    expect(content).not.toContain("<style");
    expect(css).toContain(".daily-content .card");
    expect(css).toContain(".daily-content {");
  });
});
